name: build_docker

on:
  #workflow_dispatch:
  push:
    #branches: [ main ]
    tags: ['v*.*.*' ]
      #- 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build_docker:
    name: Build docker
    runs-on: ubuntu-latest
    environment: hub_docker
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - 
        uses: rlespinasse/github-slug-action@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.GITHUB_REPOSITORY_NAME_PART }}:${{ env.GITHUB_REF_NAME }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.GITHUB_REPOSITORY_NAME_PART }}:latest
